apiVersion: v1beta1
id: monitoring-heapster-controller
kind: ReplicationController
desiredState: 
  replicas: 1
  replicaSelector:    
    name: heapster
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: monitoring-heapster
        containers:
          - name: heapster
            image: kubernetes/heapster:v0.7
            env: 
              - name: "INFLUXDB_HOST"
                value: "monitoring-influxdb"
    labels: 
      name: heapster
      uses: monitoring-influxdb
      kubernetes.io/cluster-service: "true"
labels: 
  name: heapster
  kubernetes.io/cluster-service: "true"
